"""add_provider_advanced_fields_and_experiment_status_message

Revision ID: 08c94229b6b3
Revises: 984b57b0020c
Create Date: 2026-03-28 14:56:32.460523+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '08c94229b6b3'
down_revision: Union[str, None] = '984b57b0020c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('status_message', sa.Text(), nullable=True))
    op.add_column('model_providers', sa.Column('requests_per_minute', sa.Integer(), nullable=True))
    op.add_column('model_providers', sa.Column('tokens_per_minute', sa.Integer(), nullable=True))
    op.add_column('model_providers', sa.Column('max_calls_per_experiment', sa.Integer(), nullable=True))
    op.add_column('model_providers', sa.Column('judge_api_key_enc', sa.Text(), nullable=True))
    op.add_column('model_providers', sa.Column('judge_endpoint', sa.Text(), nullable=True))
    op.add_column('model_providers', sa.Column('judge_model', sa.Text(), nullable=True))
    op.add_column('model_providers', sa.Column('use_separate_judge', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('model_providers', sa.Column('default_target_endpoint', sa.Text(), nullable=True))
    op.add_column('model_providers', sa.Column('default_system_prompt', sa.Text(), nullable=True))
    op.add_column('model_providers', sa.Column('backup_api_key_enc', sa.Text(), nullable=True))
    op.add_column('model_providers', sa.Column('backup_endpoint', sa.Text(), nullable=True))
    op.add_column('model_providers', sa.Column('backup_model', sa.Text(), nullable=True))
    op.add_column('model_providers', sa.Column('use_backup_key', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_providers', 'use_backup_key')
    op.drop_column('model_providers', 'backup_model')
    op.drop_column('model_providers', 'backup_endpoint')
    op.drop_column('model_providers', 'backup_api_key_enc')
    op.drop_column('model_providers', 'default_system_prompt')
    op.drop_column('model_providers', 'default_target_endpoint')
    op.drop_column('model_providers', 'use_separate_judge')
    op.drop_column('model_providers', 'judge_model')
    op.drop_column('model_providers', 'judge_endpoint')
    op.drop_column('model_providers', 'judge_api_key_enc')
    op.drop_column('model_providers', 'max_calls_per_experiment')
    op.drop_column('model_providers', 'tokens_per_minute')
    op.drop_column('model_providers', 'requests_per_minute')
    op.drop_column('experiments', 'status_message')
    # ### end Alembic commands ###
