"""add_system_prompt_to_projects

Revision ID: 984b57b0020c
Revises: a3f91b2c4d78
Create Date: 2026-03-28 14:23:10.598192+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '984b57b0020c'
down_revision: Union[str, None] = 'a3f91b2c4d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'system_prompt')
    # ### end Alembic commands ###
